name: Memory Leak Check

on:
  pull_request:
    branches:
      - 'main'

jobs:
  memory-leak-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Compile Program
        run: |
          make
          if [ $? -eq 0 ]; then
            echo "Compilation Success."
          else
            echo "Compilation Failed."
            exit 1
          fi

      - name: Run Valgrind
        run: |
          valgrind --leak-check=full --error-exitcode=1 ./program 2>&1 | tee valgrind_output.txt

      - name: Check Valgrind Logs
        run: |
          if grep -q "ERROR SUMMARY: 0 errors" valgrind_output.txt; then
            echo "No memory leaks detected."
          else
            echo "Memory leaks or errors detected."
            exit 1
          fi
